//insert data 
const finlandCities = 
[{"region":"Akaa"},{"region":"Alajärvi"},{"region":"Alavus"},{"region":"Espoo"},{"region":"Forssa"},{"region":"Haapajärvi"},{"region":"Haapavesi"},{"region":"Hamina"},{"region":"Hanko"},{"region":"Harjavalta"},{"region":"Haukipudas"},{"region":"Heinola"},{"region":"Helsinki"},{"region":"Huittinen"},{"region":"Hyvinkää"},{"region":"Hämeenlinna"},{"region":"Iisalmi"},{"region":"Ikaalinen"},{"region":"Imatra"},{"region":"Pietarsaari"},{"region":"Joensuu"},{"region":"Juankoski"},{"region":"Jyväskylä"},{"region":"Jämsä"},{"region":"Järvenpää"},{"region":"Kaarina"},{"region":"Kajaani"},{"region":"Kalajoki"},{"region":"Kankaanpää"},{"region":"Kannus"},{"region":"Karkkila"},{"region":"Kaskinen"},{"region":"Kauhajoki"},{"region":"Kauhava"},{"region":"Kauniainen"},{"region":"Kemi"},{"region":"Kemijärvi"},{"region":"Kerava"},{"region":"Keuruu"},{"region":"Kitee"},{"region":"Kiuruvesi"},{"region":"Kokemäki"},{"region":"Kokkola"},{"region":"Kotka"},{"region":"Kouvola"},{"region":"Kristiinankaupunki"},{"region":"Kuhmo"},{"region":"Kuopio"},{"region":"Kurikka"},{"region":"Kuusamo"},{"region":"Lahti"},{"region":"Laitila"},{"region":"Lappeenranta"},{"region":"Lapua"},{"region":"Lieksa"},{"region":"Lohja"},{"region":"Loimaa"},{"region":"Loviisa"},{"region":"Maarianhamina"},{"region":"Mikkeli"},{"region":"Mänttä-Vilppula"},{"region":"Naantali"},{"region":"Nilsiä"},{"region":"Nivala"},{"region":"Nokia"},{"region":"Nurmes"},{"region":"Uusikaarlepyy"},{"region":"Närpiö"},{"region":"Orimattila"},{"region":"Orivesi"},{"region":"Oulainen"},{"region":"Oulu"},{"region":"Outokumpu"},{"region":"Paimio"},{"region":"Parainen"},{"region":"Parkano"},{"region":"Pieksämäki"},{"region":"Pori"},{"region":"Porvoo"},{"region":"Pudasjärvi"},{"region":"Pyhäjärvi"},{"region":"Raahe"},{"region":"Raasepori"},{"region":"Raisio"},{"region":"Rauma"},{"region":"Riihimäki"},{"region":"Rovaniemi"},{"region":"Saarijärvi"},{"region":"Salo"},{"region":"Sastamala"},{"region":"Savonlinna"},{"region":"Seinäjoki"},{"region":"Siuntio"},{"region":"Somero"},{"region":"Suonenjoki"},{"region":"Tampere"},{"region":"Tornio"},{"region":"Turku"},{"region":"Ulvila"},{"region":"Uusikaupunki"},{"region":"Vaasa"},{"region":"Valkeakoski"},{"region":"Vantaa"},{"region":"Varkaus"},{"region":"Viitasaari"},{"region":"Virrat"},{"region":"Ylivieska"},{"region":"Ylöjärvi"},{"region":"Ähtäri"},{"region":"Äänekoski"}]
//mongoDb using db.regions.insertMany(finlandCities)

//db.categories.inserMany()
const sportCategories = [{"category":"AEROBIC","categoryColor":"red"},{"category":"BADMINTON","categoryColor":"yellow"},{"category":"BASKETBALL","categoryColor":"orange"},{"category":"CYCLE","categoryColor":"olive"},{"category":"FOOTBALL","categoryColor":"blue"},{"category":"GOLF","categoryColor":"teal"},{"category":"ICEHOCKEY","categoryColor":"green"},{"category":"MOTORCYCLE","categoryColor":"violet"},{"category":"SKI","categoryColor":"purple"},{"category":"TENNIS","categoryColor":"pink"},{"category":"USFOOTBALL","categoryColor":"brown"},{"category":"VOLLEYBALL","categoryColor":"facebook"}]

//if you have more categories, then use this
var sportsCategory = ["AEROBIC", "BADMINTON", "BASKETBALL", "CYCLE", "FOOTBALL", "GOLF", "ICEHOCKEY", "MOTORCYCLE", "SKI", "TENNIS", "USFOOTBALL", "VOLLEYBALL"]
var categoryColor = ["red", "yellow", "orange","olive","blue","teal","green","violet","purple","pink","brown","facebook","google plus","instagram","linkedin","twitter","vk","youtube"]

